### ISSUE TITLE
Connectors with sensitive config always show diffs leading to update

### ISSUE THREAD

**Issue by ebertn** [pulumi/pulumi-confluentcloud#182]
### What happened?

Once a connector is created with sensitive configs (for example, an Azure Eventhubs SAS key), all subsequent previews and ups will perform an `update`  even if the connector is healthy. See an example below:

```
    ~ confluentcloud:index/connector:Connector: (update)
        [id=lcc-9wq7xv]
        [urn=urn:pulumi:my_stack::my_project::confluentcloud:index/connector:Connector::my-connector]
        [provider=urn:pulumi:my_stack::my_project::pulumi:providers:confluentcloud::default_1_24_0::721b0295-ec1c-4de7-a923-d8037567a993]
      ~ configNonsensitive: {
          + azure.eventhubs.sas.key: [secret]
        }
```

I understand that the connector API doesn't return sensitive config, so it isn't possible to truly determine the diff. Is this something that we just need to live with? Is it possible to avoid updates like this if the connector's status is `running`?

NOTE: Here I'm using `configNonsensitive`, but the connector is still able to determine that my SAS key is secret

Any suggestions on how I can prevent these diffs?

### Expected Behavior

Connector that already has been created shows no diffs when previewed or up'd again

### Steps to reproduce

Create a connector with sensitive config

### Output of `pulumi about`

CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME            VERSION
azure-native    2.2.0
confluentcloud  1.24.0
python          unknown

Host     
OS       darwin
Version  13.4.1
Arch     x86_64

This project is written in python: executable='/Library/Frameworks/Python.framework/Versions/3.9/bin/python3' version='3.9.0
'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/nicholas-ebert
User           nicholas-ebert
Organizations  nicholas-ebert, daimler-mic

Dependencies:
NAME                    VERSION
automation              0.6.1
azure-identity          1.13.0
azure-keyvault-secrets  4.7.0
black                   23.7.0
pip                     23.2.1
pulumi-azure-native     2.2.0
pulumi-confluentcloud   1.24.0
pydantic                2.1.1
pytest-azurepipelines   1.0.4
pytest-cov              4.1.0
pytest-env              0.8.2
setuptools              49.2.1

Pulumi locates its logs in /var/folders/zc/xwj0l22j6q13ddpft5dmbsm9xlqk42/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @ebertn thanks for reaching out.

Please could you provide a minimal runnable code example which reproduces this issue? Thank you!
