### ISSUE TITLE
Upgrade the Pulumi provider to stay current with upgraded Confluent provider now at v0.13.0

### ISSUE THREAD

**Issue by chadccollins** [pulumi/pulumi-confluentcloud#2]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Confluent Cloud has release a new version of their Terraform provider - v0.13.0 https://registry.terraform.io/providers/confluentinc/confluent/0.13.0

I'm using Pulumi while working quite closely with Confluent and would like to be able to stay as up to date as possible with their automation. 

### Affected area/feature

Release notes for updated items here: https://github.com/confluentinc/terraform-provider-confluent/releases

**Comment by jkodroff** [comment]
@chadccollins My apologies for the delay on implementing this. Our GH automation that lets us know about upstream new releases was not correctly configured for this repository. We're fixing this in the mentioned PR above.
