### ISSUE TITLE
Adding "pulumi" user agent to this provider

### ISSUE THREAD

**Issue by linouk23** [pulumi/pulumi-confluentcloud#26]
### What
Thanks for supporting Confluent Cloud Resource Provider!

Currently both Pulumi and TF clients has the same user agent that is being generated [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/provider.go#L232) in the source code of TF Provider.

How can we make Pulumi's Confluent Cloud Resource Provider have a custom user agent? Will it be sufficient to expose `userAgent` variable [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/main.go#L24-L25) so it could be overridden? Alternatively it'd be great if you could share a code reference or something, thanks!

**Comment by danielrbradley** [comment]
Yes, the constant is defined [in the provder.go too](https://github.com/confluentinc/terraform-provider-confluent/blob/c3b183160869248558feec5e12eb8155767994af/internal/provider/provider.go#L37).

We might be able to set something like this when building to override this value:
```
-ldflags "-X github.com/confluentinc/terraform-provider-confluent/internal/provider/provider.terraformProviderUserAgent=$(VERSION)"
```
