### ISSUE TITLE
Error updating state from v0.1.0 to v1.0.0

### ISSUE THREAD

**Issue by cojam-dutchie** [pulumi/pulumi-confluentcloud#5]
### What happened?

I have been working with the v0.1.0 confluentcloud pulumi provider since shortly after it was released. I am now attempting to upgrade these project to use the v1.0.0 release. There were some deprecations/changes that needed to be made. Mostly this was just a matter of removing the `http_endpoint` and `credentials` from the resources that used to depend on them. After addressing those things, a `pulumi preview` results in `panic: interface conversion: interface {} is nil, not string`

### Steps to reproduce

Update an existing project to use pulumi_confluentcloud 1.0 and then run `pulumi preview`. In python using poetry.

1) Edit `pyproject.toml` and set target version of pulumi-confluent cloud.

```
pulumi-confluentcloud = "^1.0.0"
```

2) Update pulumi-confluent cloud

```
➜   poetry update pulumi-confluentcloud
Updating dependencies
Resolving dependencies... (0.4s)

Writing lock file

Package operations: 0 installs, 1 update, 0 removals

  • Updating pulumi-confluentcloud (0.1.0 -> 1.0.0)
```

3) Remove use of the http_endpoint and credentials properties on KafkaTopic and KafkaAcl resources.

4) Run pulumi preview

```
➜   task preview   
task: [preview] pulumi pre
Previewing update (REDACTED)

View Live: REDACTED

     Type                                  Name                                            Plan     Info
     pulumi:pulumi:Stack                   confluent-cloud.ecom-dev.common.us-east-1                27 messages     ├─ confluentcloud:index:KafkaCluster  kafka-cluster                                            1 error
     └─ confluentcloud:index:KafkaTopic    mongodbsourceconnector.topics.analytics-events           1 error
 
Diagnostics:
  confluentcloud:index:KafkaCluster (kafka-cluster):
    error: Preview failed: error reading from server: EOF
 
  confluentcloud:index:KafkaTopic (mongodbsourceconnector.topics.analytics-events):
    error: error reading from server: EOF
 
  pulumi:pulumi:Stack (confluent-cloud.ecom-dev.common.us-east-1):
    2022/07/26 13:07:32 [DEBUG] GET https://api.confluent.cloud/cmk/v2/clusters/lkc-mvpo72?environment=env-nvwdjv
    panic: interface conversion: interface {} is nil, not string
    goroutine 53 [running]:
    github.com/confluentinc/terraform-provider-confluent/internal/provider.kafkaStateUpgradeV0({0x2825588?, 0x1?}, 0x2?, {0xc00011ac18?, 0x0?})
        /home/runner/go/pkg/mod/github.com/confluentinc/terraform-provider-confluent@v1.0.0/internal/provider/state_upgraders.go:92 +0xf2
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.UpgradeJSONState({0x20a0bb0, 0xc00004c0b0}, 0x1?, 0xc00045a420?, 0xc0000b3450?, {0x1dce960, 0xc0001258c0})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220505215311-795430389fa7/helper/schema/grpc_provider.go:449 +0xa7
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.upgradeResourceState(0xc00010d0e0, 0xc0002f24b0?, 0xc000a001a0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.26.0/pkg/tfshim/sdk-v2/upgrade_state.go:44 +0x205
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0xc000410000?}, {0x1e8ffd3, 0x15}, {0x20a1710?, 0xc00087bad0}, {0x209a060, 0xc00045ab10})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.26.0/pkg/tfshim/sdk-v2/provider.go:95 +0xda
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Diff(0xc000410000, {0x20a0c20?, 0xc00045a090?}, 0xc000528c40)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.26.0/pkg/tfbridge/provider.go:756 +0x571
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0x20a0c20, 0xc00045a090}, {0x1df0a60?, 0xc000528c40})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.36.0/proto/go/provider.pb.go:3706 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x20a0c20, 0xc000413d70}, {0x1df0a60, 0xc000528c40}, 0xc00003bbe0, 0xc00062f200)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0x1e4ec00?, 0xc000410000}, {0x20a0c20, 0xc000413d70}, 0xc00010ccc0, 0xc000519760)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.36.0/proto/go/provider.pb.go:3708 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000135dc0, {0x20a5a90, 0xc000602340}, 0xc000577d40, 0xc000427e60, 0x28a3088, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfd
    google.golang.org/grpc.(*Server).handleStream(0xc000135dc0, {0x20a5a90, 0xc000602340}, 0xc000577d40, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:1620 +0xa1b
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:922 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:920 +0x28a
 

task: Failed to run task "preview": exit status 255
```

### Expected Behavior

Pulumi should seamlessly update the provider state as needed.

### Actual Behavior

Go panics and shuts down

### Versions used

CLI          
Version      3.36.0
Go Version   go1.18.4
Go Compiler  gc

Plugins
NAME            VERSION
confluentcloud  1.0.0
github          4.13.0
python          unknown

Host     
OS       darwin
Version  12.3.1
Arch     x86_64

This project is written in python: executable='/Users/cjames/.pyenv/shims/python3' version='3.10.4'

Current Stack: getdutchie/dev.common.us-east-1

TYPE                                                URN
pulumi:pulumi:Stack                                 urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::pulumi:pulumi:Stack::confluent-cloud.ecom-dev.common.us-east-1
ecom:index:MongoDbSourceConnector                   urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector::mongodbsourceconnector
pulumi:providers:confluentcloud                     urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::pulumi:providers:confluentcloud::default_0_1_0
core:index:AclConfluentInternal                     urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$core:index:AclConfluentInternal::mongodbsourceconnector.user.confluent-internal-acl
ecom:index:MongoDbSourceConnectorTopics             urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics::mongodbsourceconnector.topics
ecom:index:MongoDbSourceConnectorUser               urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser::mongodbsourceconnector.user
confluentcloud:index/serviceAccount:ServiceAccount  urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser$confluentcloud:index/serviceAccount:ServiceAccount::mongodbsourceconnector.user.sa
confluentcloud:index/kafkaCluster:KafkaCluster      urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::confluentcloud:index/kafkaCluster:KafkaCluster::kafka-cluster
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.order-traces-v2
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.protospecials
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.products
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.ordering-suspension
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.shortcodes
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.residential-address-checks
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.smartystreets
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.specials
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.tracked-carts
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.usercontacts
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.users
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.archivedorders-simplified
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.orders-simplified
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.dlq
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.heartbeat
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.devices
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.deletedproducts
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.analytics-events
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.enterprise-specials
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.coupons
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.customers
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.duplicatedproducts
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.library-products
confluentcloud:index/kafkaTopic:KafkaTopic          urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorTopics$confluentcloud:index/kafkaTopic:KafkaTopic::mongodbsourceconnector.topics.integrations
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.acl-describe-cluster
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$core:index:AclConfluentInternal$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.confluent-internal-acl.read
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.acl-write-change-events
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$core:index:AclConfluentInternal$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.confluent-internal-acl.write
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$core:index:AclConfluentInternal$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.confluent-internal-acl.describe
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.acl-read-heartbeat
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.acl-describe-change-events
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.acl-describe-heartbeat
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.acl-describe-dlq
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.acl-write-heartbeat
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.acl-group-read
confluentcloud:index/kafkaAcl:KafkaAcl              urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$ecom:index:MongoDbSourceConnectorUser$confluentcloud:index/kafkaAcl:KafkaAcl::mongodbsourceconnector.user.acl-write-dlq
confluentcloud:index/connector:Connector            urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$confluentcloud:index/connector:Connector::mongodbsourceconnector.connector_0
confluentcloud:index/connector:Connector            urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$confluentcloud:index/connector:Connector::mongodbsourceconnector.history_1420088400000_1658808000000
confluentcloud:index/connector:Connector            urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::ecom:index:MongoDbSourceConnector$confluentcloud:index/connector:Connector::mongodbsourceconnector.connector_1

Found no pending operations associated with getdutchie/dev.common.us-east-1

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/collin-dutchie
User           collin-dutchie
Organizations  collin-dutchie, getdutchie

Dependencies:
NAME                   VERSION
black                  22.3.0
flake8                 4.0.1
isort                  5.10.1
mypy                   0.950
pip                    22.2
pulumi-confluentcloud  1.0.0
pulumi-github          4.13.0
pydantic               1.9.1
yamllint               1.26.3

Pulumi locates its logs in /var/folders/x_/dc7m988x0hvby0lyndckj8tw0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cojam-dutchie** [comment]
I just noticed that ConfluentCloud is having an incident with its API right now. I'm not sure if that is or was a factor in this bug but it feels like important context. https://status.confluent.cloud/

**Comment by raytung** [comment]
We're also seeing this issue. Not sure if it's related but for what it's worth, Confluent recommends upgrading to 0.10.0 first if we are upgrading from a version earlier than 0.10.0 https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.12.0

**Comment by hoghweed** [comment]
We are experiencing the same identical issue. We've just updated from v0.1.0 to the latest v1.1.0 and nothing works about Topics management. Any update on this?

**Comment by stack72** [comment]
Folks, apologies this slipped through the net :/ I have opened a PR that fixes this up and will allow you to upgrade seemlessly
