### ISSUE TITLE
Invalid or unknown key

### ISSUE THREAD

**Issue by felleg** [pulumi/pulumi-confluentcloud#6]
### What happened?

I am unable to use credentials stored in the Pulumi stack config. Setting the environment variables `CONFLUENT_CLOUD_API_KEY` and `CONFLUENT_CLOUD_API_SECRET` seems to work.

### Steps to reproduce

Follow the installation instructions found here to configure credentials: https://www.pulumi.com/registry/packages/confluentcloud/installation-configuration/#configuring-credentials

In particular, 
```
pulumi config set confluentcloud:apiKey XXXXXXXXXXXXXX --secret \
&& pulumi config set confluentcloud:apiSecret YYYYYYYYYYYYYY --secret
```

This is my index.ts:
```typescript
import * as confluent from "@pulumi/confluentcloud";
const envName = "myEnvironment";
const env = new confluent.Environment(envName, { displayName: envName });
```

### Expected Behavior

Successful pulumi up (create an environment called "myEnvironment")

### Actual Behavior

When I do a `pulumi up`, I receive this error:
```
    error: could not validate provider configuration: 2 errors occurred:
        * Invalid or unknown key
        * Invalid or unknown key
```

### Versions used

[about.txt](https://github.com/pulumi/pulumi-confluentcloud/files/9263199/about.txt)

**Comment by stack72** [comment]
Hi @felleg 

I apologise! I will get these values updated - the instructions should read:

```
pulumi config set confluentcloud:cloudApiKey XXXXXXXXXXXXXX --secret \
&& pulumi config set confluentcloud:cloudApiSecret YYYYYYYYYYYYYY --secret
```

That will work for you 

Paul
